### PR TITLE
Set Content-Language on non GET request

### PR DESCRIPTION
**Pull request by spras**
## Checklist

- [x] Changelog updated

### CODE REVIEW

**Comment by ecourtial** [comment]
Thank you for your contribution, but we can't do it at the moment.

**Comment by spras** [comment]
Curious why this cannot be done ?

This is a bug fix: when  trying to update content on multi-lingual content, the API is based on Content-Language header  , but the SDK doesn't set this header.

**Comment by ecourtial** [comment]
We are aware of the issue but we can't do it now because of the quantity of modifications it requires so far (some work on the cassettes used for the tests).
We are going to wait for the job to make the SDK compatible with PHP8 to be finished (soon) and then reconsider your fix :)

**Comment by ecourtial** [comment]
@spras Will be added in one of our releases of this month.

**Pull request closed without merging**
